# Autoprefixer
autoprefixer:
  # https://github.com/postcss/autoprefixer#browsers
  browsers:
    - Explorer >= 10
    - ExplorerMobile >= 10
    - Firefox >= 30
    - Chrome >= 34
    - Safari >= 7
    - Opera >= 23
    - iOS >= 7
    - Android >= 4.4
    - BlackBerry >= 10

# BrowserSync
browserSync:
  browser: default # or ["google chrome" "firefox"]
  https: false # Enable https for localhost development.
  notify: false # The small pop-over notifications in the browser.
  port: 9000
